<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" targetNamespace="urn:ProfileProcessorWsd" xmlns:p0="urn:ProfileProcessorWsd/basic" xmlns:p1="urn:ProfileProcessorWsd/ssl" xmlns:p2="urn:ProfileProcessorWsd/client" xmlns:p3="urn:ProfileProcessorWsd/ticket" xmlns:tns="urn:ProfileProcessorWsd">
	<UsingPolicy xmlns="http://schemas.xmlsoap.org/ws/2004/09/policy"/>
	<wsdl:import location="file1.wsdl" namespace="urn:ProfileProcessorWsd/basic"/>
	<wsdl:import location="file3.wsdl" namespace="urn:ProfileProcessorWsd/ssl"/>
	<wsdl:import location="file4.wsdl" namespace="urn:ProfileProcessorWsd/client"/>
	<wsdl:import location="file5.wsdl" namespace="urn:ProfileProcessorWsd/ticket"/>
	<wsdl:service name="ProfileProcessor">
		<wsdl:port binding="p0:basicBinding" name="basicPort">
			<soap:address xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" location="http://vendor:50000/ProfileProcessor/basic?style=document"/>
		</wsdl:port>
		<wsdl:port binding="p1:sslBinding" name="sslPort">
			<soap:address xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" location="https://vendor:-1/ProfileProcessor/ssl?style=document"/>
		</wsdl:port>
		<wsdl:port binding="p2:clientBinding" name="clientPort">
			<soap:address xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" location="https://vendor:-1/ProfileProcessor/client?style=document"/>
		</wsdl:port>
		<wsdl:port binding="p3:ticketBinding" name="ticketPort">
			<soap:address xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" location="http://vendor:50000/ProfileProcessor/ticket?style=document"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
